################################################################################
## This file configures all of the bundles that the application will need
################################################################################

bundles:

    # bundles for all environments
    all:

        # project bundles (from src/ directory)
        - blog-admin-bundle
        - blog-api-bundle
        - blog-bundle

        # core conga bundles (from node_modules/ directory)
        - "@conga/framework-bass"
        - "@conga/framework-rest"
        - "@conga/framework-security"
        - "@conga/framework-session"
        - "@conga/framework-validation"
        - "@conga/framework-view-twig"
        - "@conga/framework-view"
        - "@conga/framework-webpack"

    # add bundles that are only used for development
    development:

        - "@conga/framework-dashboard"
        - "@conga/framework-profiler"
