################################################################################
## This file overrides config settings for the "development" environment
################################################################################

imports:
    - { resource : config.yml }

# overwrite framework configuration for the dev environment
framework:
    logger:
        # log to console for development mode
        default:
            type: console
            level: DEBUG

        # prevent the profiler from showing queries in the console
        bass.profiler:
            type: console
            level: ERROR

        # prevent the session from showing queries in the console
        bass.session:
            type: console
            level: ERROR

bass:

    logging:

        profiler: "@logger.bass.profiler"

    connections:

        profiler:
            adapter: "%profiler.database.adapter%"
            database: "%profiler.database%"
            host: "%profiler.database.host%"
            port: "%profiler.database.port%"

    managers:

        profiler:
            adapter: "%profiler.database.adapter%"
            connection: profiler
            logger: profiler
            documents:
                conga-profiler: "@conga/framework-profiler:model"


# ------------------------------------------------------------------------------
# @conga/framework-webpack
#
# This bundle provides webpack middleware for in-memory compilation and hot
# reloading in development mode. It also provides the "conga webpack:compile"
# command to compile the final production files with cache busted filenames
# ------------------------------------------------------------------------------
webpack:

    # turn development mode on/off (dev middleware / hot reloading)
    development: true

    # the public path to publish files in dev mode under
    public.path: /dist

    # the paths to all the config files
    config.paths:
        - "blog-bundle:resources/public-src/webpack.common.js"

# ------------------------------------------------------------------------------
# @conga/framework-profiler
#
# ------------------------------------------------------------------------------
profiler:
    # optional, if omitted, true is used
    # possible values are true, false, request
    # request means, only enabled for matched requests
    enabled: true

    # required
    bass:
        manager: profiler

    # optional, if omitted, true is used with defaults
    monitoring:
        enabled: true
        delay_idle: 25000
        delay_request: 500
        persist: request
        #persist: all

    # optional
#    security:
#        authenticator: '@security.firewall.authenticator.http_basic'
#        provider:
#            memory:
#                users:
#                    conga@profiler:
#                        # let-me-in
#                        password: JDJhJDEwJHJFRGFaZ3BzTFgwNUZORmVGYloxdS4wZlNhbGRQMThnMW12SGJNZ3lPOFRORjg1Vk8uNnph
#                        roles: ROLE_PROFILER

    # optional
    # if you are working on the dashboard and want to profile the requests
    profile_dashboard: false
